using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TimeKeeper.Models
{
    public class TimeKeeperDb : DbContext
    {
        public TimeKeeperDb(DbContextOptions<TimeKeeperDb> opts)
            : base(opts) { }
        public DbSet<Charge> TimeCharges { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Project> Projects { get; set; }

        public void BuildTestData()
        {
            Departments.AddRange(new Department[]
            {
                new Department() { Name = "Information Technology" } ,
                new Department() { Name = "Accounts Payable" } ,
                new Department() { Name = "Accounts Receivable" } ,
                new Department() { Name = "Marketing" } ,
                new Department() { Name = "new Business" } ,
                new Department() { Name = "Sales" } ,
                new Department() { Name = "Executives" } ,
                new Department() { Name = "Infrastructure" } ,
                new Department() { Name = "Developer" } ,
                new Department() { Name = "Maintenance" } ,
                new Department() { Name = "Operations" } ,
                new Department() { Name = "Human Resources" } ,
                new Department() { Name = "Shipping" } ,
                new Department() { Name = "Supply" } ,
                new Department() { Name = "Customer Service" } ,
                new Department() { Name = "Research and Development" } ,
                new Department() { Name = "Purchasing" } ,
                new Department() { Name = "Legal" } ,
                new Department() { Name = "Quality Assurance" } ,
                new Department() { Name = "Licensing" } ,
                new Department() { Name = "Engineering" }
            });
            Projects.AddRange(new Project[]
            {
                new Project() { ProjectName = "Project Moonshine"},
                new Project() { ProjectName = "Project Sahara"},
                new Project() { ProjectName = "Project Zulu"},
                new Project() { ProjectName = "Project Cauldron"},
                new Project() { ProjectName = "Project Bullwinkle"},
                new Project() { ProjectName = "Project Too Hot to Handle"},
                new Project() { ProjectName = "Project Voyager"},
                new Project() { ProjectName = "Project Drop it Like its Hot"},
                new Project() { ProjectName = "Project Liberation"},
                new Project() { ProjectName = "Project Durango"},
                new Project() { ProjectName = "Project Fireball"},
                new Project() { ProjectName = "Project Dagwood"},
                new Project() { ProjectName = "Project Cinnamon"},
                new Project() { ProjectName = "Project Barracuda"},
                new Project() { ProjectName = "Project Aurora"},
                new Project() { ProjectName = "Project Bordeaux"},
                new Project() { ProjectName = "Project Monkey King"},
                new Project() { ProjectName = "Project FireFly"},
                new Project() { ProjectName = "Project Eagle"},
                new Project() { ProjectName = "Project Odyssey"},
                new Project() { ProjectName = "Project Quadro"},
                new Project() { ProjectName = "Project Sunergy"},
                new Project() { ProjectName = "Project Xena"},
                new Project() { ProjectName = "Project Zeus"},
                new Project() { ProjectName = "Project Vega"},
                new Project() { ProjectName = "Project Titan"},
                new Project() { ProjectName = "Project Quicksilver"},
                new Project() { ProjectName = "Project Omega"},
                new Project() { ProjectName = "Project Piglet"},
                new Project() { ProjectName = "Project Mad Hatter"},
                new Project() { ProjectName = "Project Kodiak"},
                new Project() { ProjectName = "Project Flamingo"},
                new Project() { ProjectName = "Project Excalibur"},
                new Project() { ProjectName = "Project Deja Vu"},
                new Project() { ProjectName = "Project Elixir"},
                new Project() { ProjectName = "Project Fusion"},
                new Project() { ProjectName = "Project Kryptonite"},
                new Project() { ProjectName = "Project Malibu"},
                new Project() { ProjectName = "Project Prelude"},
                new Project() { ProjectName = "Project Yoda"},
                new Project() { ProjectName = "Project Top Cat"},
                new Project() { ProjectName = "Project Rampage"},
                new Project() { ProjectName = "Project Sputnik"},
                new Project() { ProjectName = "Project Revolution"},
                new Project() { ProjectName = "Project Yosemite"},
                new Project() { ProjectName = "Project Apollo"},
                new Project() { ProjectName = "Project Constantine"},
                new Project() { ProjectName = "Project Hydra"},
                new Project() { ProjectName = "Project Hades"},
                new Project() { ProjectName = "Project Darwin"},
                new Project() { ProjectName =  "Project Intersect"},
                new Project() { ProjectName =  "Project Helicopter"},
                new Project() { ProjectName =  "Project Tango"},
                new Project() { ProjectName =  "Project Wookiee"},
                new Project() { ProjectName =  "Project Sizzling Shrimp"},
                new Project() { ProjectName =  "Project Sandworm"},
                new Project() { ProjectName =  "Project Alma Mater"},
                new Project() { ProjectName =  "Project Truth"},
                new Project() { ProjectName =  "Project Imported Hard Salami"},
                new Project() { ProjectName =  "Project Nemesis"},
                new Project() { ProjectName =  "Project Crown Vic"},
                new Project() { ProjectName =  "Project Undercover Lover"},
                new Project() { ProjectName =  "Project Marlin"},
                new Project() { ProjectName =  "Project First Date"},
                new Project() { ProjectName =  "Project Seduction"},
                new Project() { ProjectName =  "Project Break-Up"},
                new Project() { ProjectName =  "Project Cougars"},
                new Project() { ProjectName =  "Project Tom Sawyer"},
                new Project() { ProjectName =  "Project Ex"},
                new Project() { ProjectName =  "Project Fat Lady"},
                new Project() { ProjectName =  "Project Gravitron"},
                new Project() { ProjectName =  "Project Sensei"},
                new Project() { ProjectName =  "Project DeLorean"},
                new Project() { ProjectName =  "Project Santa Claus"},
                new Project() { ProjectName =  "Project Third Dimension" },
                new Project() { ProjectName =  "Project Suburbs" },
                new Project() { ProjectName =  "Project Best Friend"},
                new Project() { ProjectName =  "Project Beefcake"},
                new Project() { ProjectName =  "Project Lethal Weapon"},
                new Project() { ProjectName =  "Project Predator"},
                new Project() { ProjectName =  "Project Broken Heart"},
                new Project() { ProjectName =  "Project Dream Job"},
                new Project() { ProjectName =  "Project First Kill"},
                new Project() { ProjectName =  "Project Colonel"},
                new Project() { ProjectName =  "Project Ring"},
                new Project() { ProjectName =  "Project Pink Slip"},
                new Project() { ProjectName =  "Project Three Words"},
                new Project() { ProjectName =  "Project Angel de la Muerte"},
                new Project() { ProjectName =  "Project Operation Awesome"},
                new Project() { ProjectName =  "Project First Class"},
                new Project() { ProjectName =  "Project Nacho Sampler"},
                new Project() { ProjectName =  "Project Mask"},
                new Project() { ProjectName =  "Project Fake Name"},
                new Project() { ProjectName =  "Project Beard"},
                new Project() { ProjectName =  "Project Tic Tac"},
                new Project() { ProjectName =  "Project Final Exam"},
                new Project() { ProjectName =  "Project American Hero"},
                new Project() { ProjectName =  "Project Other Guy"},
                new Project() { ProjectName =  "Project Honeymooners"},
                new Project() { ProjectName =  "Project Role Models"},
                new Project() { ProjectName =  "Project Tooth"},
                new Project() { ProjectName =  "Project Living Dead"},
                new Project() { ProjectName =  "Project Subway"},
                new Project() { ProjectName =  "Project Ring: Part II"},
                new Project() { ProjectName =  "Project Anniversary"},
                new Project() { ProjectName =  "Project Suitcase"},
                new Project() { ProjectName =  "Project Cubic Z"},
                new Project() { ProjectName =  "Project Coup d'Etat"},
                new Project() { ProjectName =  "Project Couch Lock"},
                new Project() { ProjectName =  "Project Aisle of Terror"},
                new Project() { ProjectName =  "Project First Fight"},
                new Project() { ProjectName =  "Project Fear of Death"},
                new Project() { ProjectName =  "Project Phase Three"},
                new Project() { ProjectName =  "Project Leftovers"},
                new Project() { ProjectName =  "Project Balcony"},
                new Project() { ProjectName =  "Project Gobbler"},
                new Project() { ProjectName =  "Project Push Mix"},
                new Project() { ProjectName =  "Project Seduction Impossible"},
                new Project() { ProjectName =  "Project Cat Squad"},
                new Project() { ProjectName =  "Project Masquerade"},
                new Project() { ProjectName =  "Project First Bank of Evil"},
                new Project() { ProjectName =  "Project A-Team"},
                new Project() { ProjectName =  "Project Muuurder"},
                new Project() { ProjectName =  "Project Family Volkoff"},
                new Project() { ProjectName =  "Project Wedding Planner"},
                new Project() { ProjectName =  "Project Agent X"},
                new Project() { ProjectName =  "Project Last Details"},
                new Project() { ProjectName =  "Project Cliffhanger"},
                new Project() { ProjectName =  "Project Zoom"},
                new Project() { ProjectName =  "Project Bearded Bandit"},
                new Project() { ProjectName =  "Project Frosted Tips"},
                new Project() { ProjectName =  "Project Business Trip"},
                new Project() { ProjectName =  "Project Hack Off"},
                new Project() { ProjectName =  "Project Curse"},
                new Project() { ProjectName =  "Project Santa Suit"},
                new Project() { ProjectName =  "Project Baby"},
                new Project() { ProjectName =  "Project Kept Man"},
                new Project() { ProjectName =  "Project Bo" },
                new Project() { ProjectName =  "Project Bullet Train"},
                new Project() { ProjectName =  "Project Sarah"},
                new Project() { ProjectName =  "Project Goodbye"},

            });
            SaveChanges();
        }
    }
}
